### PR TITLE
Fix oauth cross platform browser open

### LINKED ISSUE #17: Trying to follow example
**Description**

I was following the steps in the README.md but when I try to sign I just get:

```
[midawson@midawson sigstore-js]$ ./bin/sigstore.js sign ./node-addon-api-4.3.0.tgz >signature
Error: No identity token provided
    at Signer.getIdentityToken (/home/midawson/sigstore/sigstore-js/dist/sign.js:59:15)
    at async Signer.sign (/home/midawson/sigstore/sigstore-js/dist/sign.js:21:31)
    at async sign (/home/midawson/sigstore/sigstore-js/dist/cli/index.js:48:23)
    at async cli (/home/midawson/sigstore/sigstore-js/dist/cli/index.js:27:13)
    at async Object.processArgv (/home/midawson/sigstore/sigstore-js/dist/cli/index.js:79:9)
```

I'm running on RHEL 8.  Is there some additional configurationt that I need to get the brower window to pop up ?

**Version**

built from main on  Aug 3 2022

### PR DESCRIPTION
**Pull request by eddiezane**
This PR adds support for opening URLs in Linux and Windows.

Fixes #17

### CODE REVIEW

File: src/identity/oauth.ts [hunk 1]
```diff
@@ -113,6 +113,8 @@ export class OAuthProvider implements Provider {
     // Open browser to start authorization request
     const authBaseURL = await this.issuer.authEndpoint();
     const authURL = this.getAuthRequestURL(authBaseURL);
+    // DO NOT SUBMIT
+    // TOOD: This failure is swallowed. How do we raise this?
     await this.openURL(authURL);
```
Comment (eddiezane) [inline src/identity/oauth.ts:118]: This rejected promise is swallowed and I am not sure where to throw it.

File: src/identity/oauth.ts [hunk 2]
```diff
@@ -175,10 +177,26 @@ export class OAuthProvider implements Provider {
...
+      switch (process.platform) {
+        case 'darwin':
+          open = 'open';
+          break;
+        case 'linux':
+          open = 'xdg-open';
+          break;
+        case 'win32':
+          open = 'start';
+          command = `"" ${command}`
```
Comment (eddiezane) [inline src/identity/oauth.ts:193]: Need to confirm this in a Windows vm.

Comment (eddiezane) [reply src/identity/oauth.ts]: Confirmed this works.

File: src/identity/oauth.ts (hunk 1 above)
Comment (bdehamer) [reply src/identity/oauth.ts:118]: I think this may be as simple as removing the `.catch` on this line:

https://github.com/github/sigstore-js/blob/main/src/sign.ts#L111

This is swallowing any errors which are thrown from within an identity provider. This code has been through a lot of refactoring and it may have made sense to swallow these errors in some past iteration, but I don't think it does anymore.

File: src/identity/oauth.ts [hunk 3]
```diff
@@ -175,10 +181,26 @@ export class OAuthProvider implements Provider {
...
+          open = 'xdg-open';
+          break;
+        case 'win32':
+          open = 'start';
+          command = `"" ${command}`;
+          break;
+        default:
+          return reject(`OAuth: unsupported platform: ${process.platform}`);
+      }
+      console.log(`Your browser will now be opened to: ${url}`);
```
Comment (bdehamer) [inline src/identity/oauth.ts:202]: I think we might want to send this to stderr w/ `console.error` (similar to how it's done in [cosign](https://github.com/sigstore/sigstore/blob/ca3b544f985f87114485ffa686dd558f80357449/pkg/oauth/oidc/interactive.go#L186)). That way if you're redirecting the output of the command to a file to capture the signature/attestation you won't also get this string.

File: src/identity/oauth.test.ts [hunk 4]
```diff
@@ -36,6 +36,12 @@ describe('OAuthProvider', () => {
     mockedExec.mockReset();
   });
 
+  const mockedConsoleLog = jest.spyOn(console, 'log').mockImplementation();
+
+  afterAll(() => {
+    mockedConsoleLog.mockRestore();
+  });
```
Comment (bdehamer) [inline src/identity/oauth.test.ts:43]: If we send the "Your browser will open..." message to stderr we can ditch this bit -- I've already got `console.error` stubbed out [here](https://github.com/sigstore/sigstore-js/blob/main/jest.setup.js#L16).

**Review by bdehamer — CHANGES_REQUESTED** [review]
Looks good. Just one small request wrt to the "Your browser will open..." message. Thanks!

File: src/identity/oauth.ts (hunk 3 above)
Comment (eddiezane) [reply src/identity/oauth.ts]: Great catch!

**Review by bdehamer — APPROVED** [review]
Nice!

**Review by cpanato — APPROVED** [review]
approving because was already approve by a mantainer, just to unblock and get this merged, was just a rebase
